import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Sparkles, AtSign } from "lucide-react";
import Input from "../components/ui/Input";
import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import { useAuth } from "../hooks/useAuth";
import { useToast } from "../providers/ToastProvider";
import { supabase } from "../lib/supabaseClient";

const USERNAME_RE = /^[a-z0-9_]{3,24}$/;

// Strip the random "_a1b2c3" suffix the trigger appends to autogenerated handles
// so we can suggest a clean default (e.g. "juan_a1b2c3" -> "juan").
function suggestUsername(raw?: string) {
  return (raw || "").replace(/_[0-9a-f]{6}$/i, "");
}

export default function OnboardingPage() {
  const { user, profile, refreshProfile, signOut } = useAuth();
  const [name, setName] = useState(profile?.name || "");
  const [username, setUsername] = useState(suggestUsername(profile?.username));
  const [saving, setSaving] = useState(false);
  const navigate = useNavigate();
  const toast = useToast();

  // The profile may resolve after mount; prefill once it arrives (without
  // clobbering anything the user already typed).
  useEffect(() => {
    if (!profile) return;
    setName((n) => n || profile.name || "");
    setUsername((u) => u || suggestUsername(profile.username));
  }, [profile]);

  const cleanUsername = username.trim().toLowerCase();
  const usernameValid = USERNAME_RE.test(cleanUsername);

  const handleSave = async () => {
    if (!user) return;
    if (!usernameValid) {
      return toast.error("El usuario debe tener 3-24 caracteres: letras, números o _");
    }
    setSaving(true);
    // Upsert (not update): the row may not exist for accounts created before the
    // handle_new_user trigger. Insert if missing, update if present.
    const { error } = await supabase
      .from("profiles")
      .upsert(
        { id: user.id, name: name.trim(), username: cleanUsername, onboarded: true },
        { onConflict: "id" }
      );
    setSaving(false);
    if (error) {
      if (error.code === "23505") return toast.error("Ese usuario ya está en uso, prueba otro.");
      return toast.error(error.message);
    }
    await refreshProfile();
    toast.success("¡Listo! Bienvenido a Rivo.");
    navigate("/");
  };

  return (
    <div className="mx-auto flex min-h-screen max-w-md items-center px-6 py-12">
      <Card className="w-full">
        <div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-brand-100 text-brand-600 dark:bg-brand-500/15 dark:text-brand-300">
          <Sparkles className="h-6 w-6" />
        </div>
        <h1 className="text-2xl font-semibold">Elige tu usuario</h1>
        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
          Así te encontrarán tus amigos para registrar deudas. Podrás cambiarlo luego.
        </p>
        <div className="mt-6 space-y-4">
          <div>
            <label className="field-label">Nombre</label>
            <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Tu nombre" />
          </div>
          <div>
            <label className="field-label">Usuario</label>
            <div className="relative">
              <AtSign className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <Input
                style={{ paddingLeft: "2.25rem" }}
                value={username}
                onChange={(e) => setUsername(e.target.value.toLowerCase())}
                placeholder="tu_usuario"
                onKeyDown={(e) => {
                  if (e.key === "Enter" && name.trim() && usernameValid) handleSave();
                }}
              />
            </div>
            {username && !usernameValid ? (
              <p className="mt-1 text-xs text-rose-500">3-24 caracteres: letras, números o guion bajo.</p>
            ) : null}
          </div>
          <Button
            fullWidth
            size="lg"
            loading={saving}
            disabled={!name.trim() || !usernameValid}
            onClick={handleSave}
          >
            Guardar y continuar
          </Button>
        </div>

        <button
          onClick={() => signOut()}
          className="mt-5 w-full text-center text-xs text-slate-400 underline-offset-2 transition hover:text-slate-600 hover:underline dark:hover:text-slate-300"
        >
          ¿No eres tú o quieres usar otra cuenta? Cerrar sesión
        </button>
      </Card>
    </div>
  );
}
